=== YeoJiSu/AdvancedWeb-study-blog/JS/XML처리/studentDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
<!ELEMENT students (student+)>
<!ELEMENT student (name,studentID,sex)>
<!ATTLIST student num CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT studentID (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
]>

=== YeoJiSu/AdvancedWeb-study-blog/JS/XML처리/xmlData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students
SYSTEM "studentDTD.dtd">
<students>
	<student num="0">
		<name>이름</name>
		<studentID>학번</studentID>
		<sex>male</sex>
	</student>
	<student num="1">
		<name>홍길동</name>
		<studentID>123456789</studentID>
		<sex>남자</sex>
	</student>
	<student num="2">
		<name>장금이</name>
		<studentID>987654321</studentID>
		<sex>여자</sex>
	</student>
</students>
